{% set name = "wandb" %}
{% set version = "0.15.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/wandb-{{ version }}.tar.gz
  sha256: b896d4043b45407d09a43ba5348da0b1b9f425a2591f45307f633d3b88d26ebf


build:
  number: 0
  noarch: python
  entry_points:
    - wandb=wandb.cli.cli:cli
    - wb=wandb.cli.cli:cli
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - click >=7.0,!=8.0.0
    - docker-pycreds >=0.4.0
    - gitpython >=1.0.0,!=3.1.29
    - pathtools
    - protobuf >=3.19.0,!=4.21.0,<5
    - psutil >=5.0.0
    - python >=3.6
    - pyyaml
    - requests >=2.0.0,<3
    - sentry-sdk >=1.0.0
    - setproctitle
    - setuptools
    - appdirs >=1.4.3
    - typing_extensions

test:
  imports:
    - wandb
  commands:
    - pip check
    - wandb --help
    - wb --help
  requires:
    - pip

about:
  home: https://github.com/wandb/client
  license: MIT
  license_file: LICENSE
  summary: A CLI and library for interacting with the Weights and Biases API.
  doc_url: https://docs.wandb.com/
  dev_url: https://github.com/wandb/client

extra:
  recipe-maintainers:
    - mxr-conda
    - rluria14
    - oblute
    - ndmaxar
    - vanpelt
    - andrewtruong
    - raubitsj
    - synapticarbors
