conda_forge_output_validation: true
bot:
  automerge: false
  inspection: update-grayskull
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  pkg_format: '2'
build_platform:
  osx_64: linux_64
provider:
  osx_64: azure